<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Movies.Core\Movies.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Movies.Infrastructure.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\resources\mymoviedb.csv" Link="Data\mymoviedb.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
